import frappe


def execute():
    """Fast teardown of imported Master Cards + their generated Product Bundles and Items.

    Uses direct SQL rather than frappe.delete_doc: the ORM path enqueues a
    delete_dynamic_links background job per document, which floods the queue
    (and trips the max-queued-jobs guard) at import scale.
    """
    mc_names = [r["name"] for r in frappe.db.sql("select name from `tabMaster Card`", as_dict=True)]
    print("Master Cards to clean:", len(mc_names))
    if not mc_names:
        print("Nothing to do.")
        return

    # Items generated by _ensure_bundle_item / _sync_fg_items are named
    # "<mcno>" (bundle) and "<mcno><LETTER>" (components). The component names
    # are recorded on the child rows, so read them rather than pattern-matching
    # tabItem (a 14k-name regexp does not scale).
    item_names = set(mc_names)
    item_names.update(
        r["item_code"]
        for r in frappe.db.sql(
            "select distinct item_code from `tabMaster Card Item` where ifnull(item_code,'') != ''",
            as_dict=True,
        )
    )
    item_names = [n for n in item_names if n]
    # Only ever touch Items in the groups the Master Card logic manages, so a
    # name collision with unrelated stock cannot delete real data.
    managed_groups = ("Master Card", "Sub Assemblies", "Component")
    safe_names = []
    for i in range(0, len(item_names), 1000):
        chunk = tuple(item_names[i : i + 1000])
        safe_names.extend(
            r["name"]
            for r in frappe.db.sql(
                "select name from tabItem where name in %(names)s and item_group in %(groups)s",
                {"names": chunk, "groups": managed_groups},
                as_dict=True,
            )
        )
    item_names = safe_names
    print("Generated Items to clean:", len(item_names))

    def bulk_delete(table, column, values):
        if not values:
            return 0
        total = 0
        for i in range(0, len(values), 1000):
            chunk = tuple(values[i : i + 1000])
            frappe.db.sql(f"delete from `{table}` where `{column}` in %(vals)s", {"vals": chunk})
            total += len(chunk)
        return total

    # Child tables of Master Card
    for child in ("Master Card Item", "Master Card Price Item", "Master Card MOQ", "Master Card Process"):
        frappe.db.sql(f"delete from `tab{child}` where parenttype = 'Master Card'")

    # Product Bundle + its child rows
    bulk_delete("tabProduct Bundle Item", "parent", mc_names)
    bulk_delete("tabProduct Bundle", "name", mc_names)

    # Items + their common child tables
    if item_names:
        for child in ("tabUOM Conversion Detail", "tabItem Default", "tabItem Barcode", "tabItem Reorder"):
            bulk_delete(child, "parent", item_names)
        bulk_delete("tabItem", "name", item_names)

    bulk_delete("tabMaster Card", "name", mc_names)

    frappe.db.commit()
    print("Remaining -> Master Card:", frappe.db.count("Master Card"))
    print("Remaining -> Master Card Item:", frappe.db.count("Master Card Item"))
    print("Remaining -> Product Bundle:", frappe.db.count("Product Bundle"))
    print("Remaining -> Item:", frappe.db.count("Item"))
